### ISSUE TITLE
Running twitchbot does not remove current text

### ISSUE THREAD

**Issue by hroafelme** [gpittarelli/reddit-twitch-bot#2]
When running twitchbot it only adds more text and never removes any.

A nice feature would also be to add images like http://streambadge.com/ and upload for example http://streambadge.com/twitch/gamesdonequick.png as %%stream-status%%

**Comment by gpittarelli** [comment]
I'm not able to reproduce the issue. Could you provide a more complete test case?

For the stream badges, I think some users have uploaded the avatars for the channels they want and then setup the stylesheet however they want to display the avatar. The bot polls every stream's status already, so the behavior is the same. The only real issue is if the stream's avatar changes. I'll look into that...

**Comment by hroafelme** [comment]
Okey, Im running Python27 on Windows 8. Other than just adding the info to config I have made no changes. I new to Python so I might have messes something up with the installs, if no one else have reported this error. But basically I used GamesDoneQuick to test and just upload stream-name to the sidebar and it just addes the name over and over again. 

> GamesDoneQuick  GamesDoneQuick  GamesDoneQuick  GamesDoneQuick  GamesDoneQuick 

Might it be a parse error with Python27 maybe?

However I went ahead with the steambadge idea and created a bot that downloads the current steambadge png and uploads it to the subreddit as %%steam-status%%

I can paste the code if you want it, but I'm a little ashamed since it's just a copy/paste from several scripts and stackoverflows and just a mess, but hey it works and I basically had 0 Python experience 4 days ago. 

I'll try reproduce it myself and report back.
